int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int sqrt_binary_search(int n, int start, int stop);
int is_prime_number(int n);
int search_prime(int n, int div);
int is_palindrome(char *s);
